### ISSUE TITLE
License

### ISSUE THREAD

**Issue by comodoro** [MrYuriyS/15puzzle#1]
Hi, I have come across your game, one of a surprisingly small amount of open sourced Android games, and was wondering about the license to it, without a specified license it is not free and people can not legally modify it under their name (although I imagine some do).

**Comment by suoapvs** [comment]
Hello, added [License](https://github.com/YuriiSalimov/15-puzzle/blob/master/LICENSE).

**Comment by comodoro** [comment]
Thank you!
